title: Technical Cider
description: Cider recipe simplified, technicalized, then pageified.
theme: just-the-docs

url: https://goooral.github.io/just-the-technical-cider

aux_links:
  Template Repository: https://github.com/goooral/just-the-technical-cider

color_scheme: dark